coup_de_patte/config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  resources :locations, only: [:index, :show, :new, :create, :edit, :update]

  resources :type_taches

  resources :animals do
    member do
      put :remove_from_farm
    end
  end

  resources :fermes

  resources :especes

  root 'animals#index'

end

coup_de_patte/app/models/ferme.rb
class Ferme < ActiveRecord::Base
  has_many :animals
  belongs_to :user
  validates_presence_of :nom
end

coup_de_patte/app/controllers/fermes_controller.rb
class FermesController < ApplicationController
  before_action :set_ferme, only: [:show, :edit, :update, :destroy]

  # GET /fermes
  # GET /fermes.json
  def index
    @fermes = Ferme.all
  end

  # GET /fermes/1
  # GET /fermes/1.json
  def show
    @animal = Animal.new
    @animal.ferme_id = params[:id]
    @especes = Espece.all
    @status_animals = StatusAnimal.all
    if(user_signed_in?)
      @fermes = Ferme.where(user_id: current_user.id)
    end
  end

  # GET /fermes/new
  def new
    @ferme = Ferme.new
    authorize! :create, Ferme, :message => "Vous n'avez pas l'autorisation"
    @animals = Animal.where(user_id: current_user.id)
  end

  # GET /fermes/1/edit
  def edit
    @ferme = Ferme.find(params[:id])
    authorize! :update, @ferme, :message => "Vous n'avez pas l'autorisation"
    @animals = Animal.where(user_id: current_user.id)
  end

  # POST /fermes
  # POST /fermes.json
  def create
    @ferme = Ferme.new(ferme_params)
    @ferme.user_id = current_user.id
    authorize! :create, @ferme, :message => "Vous n'avez pas l'autorisation"

    #updating Animals
    if params[:ferme][:animals]
      for id_animal in params[:ferme][:animals]
        aAnimal = Animal.find(id_animal)
        @ferme.animals << aAnimal
      end
    end

    respond_to do |format|
      if @ferme.save
        format.html { redirect_to @ferme, notice: 'Ferme was successfully created.' }
        format.json { render :show, status: :created, location: @ferme }
      else
        @animals = Animal.where(user_id: current_user.id)
        format.html { render :new }
        format.json { render json: @ferme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fermes/1
  # PATCH/PUT /fermes/1.json
  def update
    authorize! :update, @ferme, :message => "Vous n'avez pas l'autorisation"

    #updating Animals
    @ferme.animals.each do |aAnimal|
      @ferme.animals.delete(aAnimal)
    end
    if params[:ferme][:animals]
      for id_animal in params[:ferme][:animals]
        aAnimal = Animal.find(id_animal)
        @ferme.animals << aAnimal
      end
    end

    respond_to do |format|
      if @ferme.update(ferme_params)
        format.html { redirect_to @ferme, notice: 'Ferme was successfully updated.' }
        format.json { render :show, status: :ok, location: @ferme }
      else
        @animals = Animal.where(user_id: current_user.id)
        format.html { render :edit }
        format.json { render json: @ferme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fermes/1
  # DELETE /fermes/1.json
  def destroy
    authorize! :delete, @ferme, :message => "Vous n'avez pas l'autorisation"
    @ferme.destroy
    respond_to do |format|
      format.html { redirect_to fermes_url, notice: 'Ferme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ferme
      @ferme = Ferme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ferme_params
      params.require(:ferme).permit(:nom, :adresse, :gerant_id)
    end
end

coup_de_patte/app/helpers/fermes_helper.rb
module FermesHelper
end

coup_de_patte/app/views/fermes/_actions_specifiques.html.erb
<h2>Actions spécifiques</h2>
<% if action.eql?("index") %>
    <% if can? :manage, Ferme %>
        <%= link_to 'Nouvelle ferme', new_ferme_path %>
    <% end %>
<% end %>
<% if action.eql?("new") %>
    <%= link_to 'Retour', fermes_path %>
<%end%>
<% if action.eql?("edit") %>
    <%= link_to 'Afficher', ferme_path(@ferme) %>
    <br />
    <% if can? :manage, Ferme %>
        <%= link_to 'Nouvelle ferme', new_ferme_path %>
    <% end %>
<%end%>
<% if action.eql?("show") %>
    <% if can? :manage, @ferme %>
        <%= link_to 'Mettre à jour', edit_ferme_path(@ferme) %>
        <br />
    <% end %>
    <% if can? :manage, Ferme %>
        <%= link_to 'Nouvelle ferme', new_ferme_path %>
    <% end %>
<%end%>

coup_de_patte/app/views/fermes/_form.html.erb
<%= form_for(@ferme) do |f| %>
    <% if @ferme.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ferme.errors.count, "error") %> prohibited this ferme from being saved:</h2>

          <ul>
            <% @ferme.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :nom %><br>
      <%= f.text_field :nom %>
    </div>
    <div class="field">
      <%= f.label :adresse %><br>
      <%= f.text_field :adresse %>
    </div>
    <%= f.label "Animaux" %><br>
    <table class="table table-striped table-hover table-bordered table-responsive">
      <thead>
      <tr>
        <th>Nom</th>
        <th>Status</th>
        <th>Prix journalier</th>
        <th>Ferme</th>
        <th>Espece</th>
        <th>Taches possibles</th>
        <th></th>
        <th>Dans cette ferme</th>
      </tr>
      </thead>

      <tbody id="animals">
      <% for animal in @animals %>
          <tr>
            <%= render :partial => 'animals/animal', :locals => {:animal => animal, :printFarm => true, :printRemoveFarm => false} %>
            <td><%= check_box_tag "ferme[animals][]", animal.id, @ferme.animals.include?(animal) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <div class="actions">
      <%= f.submit :class => "btn btn-sm btn-default", :class => "btn btn-sm btn-default" %>
    </div>
<% end %>

coup_de_patte/app/views/fermes/edit.html.erb
<% content_for :actions_specifiques do %>
    <%= render :partial => "actions_specifiques",
               :locals => {:action => "edit" } %>
<% end %>
<h1>Modification d'une ferme</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @ferme %> |
<%= link_to 'Retour', fermes_path %>

coup_de_patte/app/views/fermes/index.html.erb
<% content_for :actions_specifiques do %>
    <%= render :partial => "actions_specifiques", :locals => {:action => "index" } %>
<% end %>

<h1>Liste des fermes</h1>

<table class="table table-striped table-hover table-bordered table-responsive">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Adresse</th>
      <th>Gerant</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fermes.each do |ferme| %>
      <tr>
        <td><%= ferme.nom %></td>
        <td><%= ferme.adresse %></td>
        <td><%= ferme.user.nom + " " + ferme.user.prenom %></td>
        <td>
          <%= link_to 'Afficher', ferme, :class => 'btn btn-sm btn-default' %>
          <% if can? :manage, ferme %>
            <%= link_to 'Modifier', edit_ferme_path(ferme), :class => 'btn btn-sm btn-default' %>
            <%= link_to 'Détruire', ferme, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :manage, Ferme %>
    <%= link_to 'Nouvelle ferme', new_ferme_path %>
<% end %>

coup_de_patte/app/views/fermes/new.html.erb
<% content_for :actions_specifiques do %>
    <%= render :partial => "actions_specifiques",
               :locals => {:action => "new" } %>
<% end %>
<h1>Nouvelle ferme</h1>

<%= render 'form' %>

<%= link_to 'Retour', fermes_path %>

coup_de_patte/app/views/fermes/show.html.erb
<% content_for :actions_specifiques do %>
    <%= render :partial => "actions_specifiques",
               :locals => {:action => "show" } %>
<% end %>

<h1>Ferme</h1>

<p>
  <strong>Nom:</strong>
  <%= @ferme.nom %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @ferme.adresse %>
</p>

<p>
  <strong>Gerant:</strong>
  <br/>
  <%= @ferme.user.nom + " " + @ferme.user.prenom %>
  <br/>
  <%= @ferme.user.telephone %>
</p>


<p><strong>Animaux de la ferme :</strong></p>

<table class="table table-striped table-hover table-bordered table-responsive">
  <thead>
  <tr>
    <th>Nom</th>
    <th>Status</th>
    <th>Prix journalier</th>
    <th>Espece</th>
    <th>Taches possibles</th>
    <th></th>
  </tr>
  </thead>

  <tbody id="animals">
  <% @ferme.animals.each do |animal| %>
    <tr>
      <%= render :partial => 'animals/animal', :locals => {:animal => animal, :printFarm => false, :printRemoveFarm => true} %>
    </tr>
  <% end %>
  </tbody>
</table>

<% if can? :manage, @ferme %>
    <br/>
    <div style="border: 2px solid;">
        <p><strong>Ajouter un animal</strong></p>
        <%= render :partial => "animals/form", :locals => {:isRemote => true, :fixedFarm => true} %>
    </div>
    <%= link_to 'Modifier', edit_ferme_path(@ferme) %> |
<% end %>
<%= link_to 'Retour', fermes_path %>