coup_de_patte/config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  resources :locations, only: [:index, :show, :new, :create, :edit, :update]

  resources :type_taches

  resources :animals do
    member do
      put :remove_from_farm
    end
  end

  resources :fermes

  resources :especes

  root 'animals#index'

end

coup_de_patte/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)

    if user.has_role?(:Admin)
      can :read, :all

      can :manage, Espece
      can :manage, TypeTache

      can :voir_roles, User
    end

    if user.has_role?(:Gerant)
      can :read, :all

      #Gerant can manage his own farms
      can :manage, Ferme do |ferme|
        ferme.user.id == user.id
      end

      #Gerant can manage his own animals
      can :manage, Animal do |animal|
        animal.user.id == user.id
      end


      can :update, Location do |location|
        location.animal.user.id == user.id
      end
    end

    if user.has_role?(:Paysan)
      can :read, :all

      #Paysan peut louer un animal (créer une location)
      can :create, Location
    end
  end
end

coup_de_patte/app/models/admin.rb
class Admin < User
end

coup_de_patte/app/models/animal.rb
class Animal < ActiveRecord::Base
  has_and_belongs_to_many :type_tache
  belongs_to :status_animal
  belongs_to :espece
  belongs_to :ferme
  belongs_to :user
  has_many :locations

  validates_presence_of :nom
  validates_presence_of :status_animal
  validates_presence_of :prix_journalier
  validates_presence_of :user
  validates_presence_of :espece
end

coup_de_patte/app/models/espece.rb
class Espece < ActiveRecord::Base
  has_many :animals
  validates_presence_of :nom
end

coup_de_patte/app/models/ferme.rb
class Ferme < ActiveRecord::Base
  has_many :animals
  belongs_to :user
  validates_presence_of :nom
end

coup_de_patte/app/models/gerant.rb
class Gerant < User
  has_many :fermes
  has_many :animals
end

coup_de_patte/app/models/location.rb
class Location < ActiveRecord::Base
  has_and_belongs_to_many :type_tache
  belongs_to :status_location
  belongs_to :animal
  belongs_to :user

  validates_presence_of :date
  validates_presence_of :dureeJour
  validates_presence_of :animal
  validates_presence_of :user
  validates_presence_of :status_location
end

coup_de_patte/app/models/paysan.rb
class Paysan < User
  has_many :locations
end

coup_de_patte/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

coup_de_patte/app/models/status_animal.rb
class StatusAnimal < ActiveRecord::Base
  has_many :animals
  validates_presence_of :nom
end

coup_de_patte/app/models/status_location.rb
class StatusLocation < ActiveRecord::Base
  has_many :locations
  validates_presence_of :nom
end

coup_de_patte/app/models/type_tache.rb
class TypeTache < ActiveRecord::Base
  has_and_belongs_to_many :animals
  has_and_belongs_to_many :locations

  validates_presence_of :nom
end

coup_de_patte/app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles

  has_many :animals
  has_many :fermes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  def has_role?(role)
    # faire attention à la case, tous les modifications de case invalide la vérification de rôle
    # return self.roles.find_by(:name => role.to_s.upcase)

    return self.roles.find_by(:name => role.to_s)
  end

  def roles_as_text
    texte = ''
    self.roles.each do |role|
      texte = texte + role.name + ' '
    end

    return texte[0...-1] # enlever le dernier charactère
  end

  def full_name
    "#{prenom} #{nom}"
  end
end

coup_de_patte/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end
end

coup_de_patte/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => :index

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    authorize! :read, @user, :message => "Vous n'avez pas l'autorisation"
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:nom, :prenom, :telephone)
  end
end

coup_de_patte/app/helpers/animals_helper.rb
module AnimalsHelper
end

coup_de_patte/app/helpers/application_helper.rb
module ApplicationHelper
end

coup_de_patte/app/helpers/especes_helper.rb
module EspecesHelper
end

coup_de_patte/app/helpers/fermes_helper.rb
module FermesHelper
end

coup_de_patte/app/helpers/locations_helper.rb
module LocationsHelper
end

coup_de_patte/app/helpers/roles_helper.rb
module RolesHelper
end

coup_de_patte/app/helpers/type_taches_helper.rb
module TypeTachesHelper
end

coup_de_patte/app/helpers/users_helper.rb
module UsersHelper
end

coup_de_patte/app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-sm btn-default" %>
  </div>
<% end %>

coup_de_patte/app/views/roles/edit.html.erb
<h1>Modification d'un role</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @role %> |
<%= link_to 'Retour', roles_path %>

coup_de_patte/app/views/roles/index.html.erb
<h1>Liste des roles</h1>

<table class="table table-striped table-hover table-bordered table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Afficher', role %></td>
        <td><%= link_to 'Modifier', edit_role_path(role) %></td>
        <td><%= link_to 'Détruire', role, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau rôle', new_role_path %>

coup_de_patte/app/views/roles/new.html.erb
<h1>Nouveau role</h1>

<%= render 'form' %>

<%= link_to 'Retour', roles_path %>

coup_de_patte/app/views/roles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<%= link_to 'Modifier', edit_role_path(@role) %> |
<%= link_to 'Retour', roles_path %>

coup_de_patte/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>

  <div class="field">
    <%= f.label :prenom %><br>
    <%= f.text_field :prenom %>
  </div>

  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-sm btn-default" %>
  </div>
<% end %>

coup_de_patte/app/views/users/edit.html.erb
<h1>Modification d'un utilisateur</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @user %> |
<%= link_to 'Retour', users_path %>

coup_de_patte/app/views/users/index.html.erb
<h1>Liste des utilisateurs</h1>

<table class="table table-striped table-hover table-bordered table-responsive">
  <thead>
  <tr>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Email</th>
    <th>Téléphone</th>


    <% if can? :voir_roles, current_user %>
      <th>Rôles</th>
    <% end %>

    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.nom %></td>
      <td><%= user.prenom %></td>
      <td><%= user.email %></td>
      <td><%= user.telephone %></td>

      <% if can? :voir_roles, user %>
        <td><%= user.roles_as_text %></td>
      <% end %>

      <td><%= link_to 'Afficher', user %></td>
      <td><%= link_to 'Modifier', edit_user_path(user) %></td>

      <!--<% if can? :manage, user %>-->
        <td><%= link_to 'Edit Rôles', edit_roles_user_path(user) %></td>

        <td><%= link_to 'Détruire', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger' %></td>
      <!--<% end %>-->

    </tr>
  <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'Nouveau utilisateur', new_user_path %>-->

coup_de_patte/app/views/users/new.html.erb
<h1>Nouveau utilisateur</h1>

<%= render 'form' %>

<%= link_to 'Retour', users_path %>

coup_de_patte/app/views/users/show.html.erb
<h1>Utilisateur</h1>

<p>
  <strong>Nom:</strong>
  <%= @user.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @user.prenom %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @user.telephone %>
</p>

<%= link_to 'Modifier', edit_user_path(@user) %> |
<%= link_to 'Retour', users_path %>