coup_de_patte/config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  resources :locations, only: [:index, :show, :new, :create, :edit, :update]

  resources :type_taches

  resources :animals do
    member do
      put :remove_from_farm
    end
  end

  resources :fermes

  resources :especes

  root 'animals#index'

end

coup_de_patte/app/models/animal.rb
class Animal < ActiveRecord::Base
  has_and_belongs_to_many :type_tache
  belongs_to :status_animal
  belongs_to :espece
  belongs_to :ferme
  belongs_to :user
  has_many :locations

  validates_presence_of :nom
  validates_presence_of :status_animal
  validates_presence_of :prix_journalier
  validates_presence_of :user
  validates_presence_of :espece
end

coup_de_patte/app/controllers/animals_controller.rb
# encoding: utf-8
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy, :remove_from_farm]


  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
    authorize! :create, Animal, :message => "Vous n'avez pas l'autorisation"
    @especes = Espece.all
    @status_animals = StatusAnimal.all
    @fermes = Ferme.where(user_id: current_user.id)
  end

  # GET /animals/1/edit
  def edit
    @animal = Animal.find(params[:id])
    authorize! :update, Animal, :message => "Vous n'avez pas l'autorisation"
    @especes = Espece.all
    @status_animals = StatusAnimal.all
    @fermes = Ferme.where(user_id: current_user.id)
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)
    @animal.user_id = current_user.id
    authorize! :create, @animal, :message => "Vous n'avez pas l'autorisation"
    if !@animal.ferme.nil?
      authorize! :manage, @animal.ferme, :message => "Vous n'avez pas l'autorisation"
    end

    #updating TypeTaches
    if params[:animal][:type_taches]
      for id_type_tache in params[:animal][:type_taches]
        aType = TypeTache.find(id_type_tache)
        @animal.type_tache << aType
      end
    end

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
        format.js { render 'fermes/ajoutAnimal' }
      else
        @especes = Espece.all
        @status_animals = StatusAnimal.all
        @fermes = Ferme.where(user_id: current_user.id)
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    authorize! :update, @animal, :message => "Vous n'avez pas l'autorisation"
    if !@animal.ferme.nil?
      authorize! :manage, @animal.ferme, :message => "Vous n'avez pas l'autorisation"
    end

    #updating TypeTaches
    @animal.type_tache.each do |aType|
      @animal.type_tache.delete(aType)
    end
    if params[:animal][:type_taches]
      for id_type_tache in params[:animal][:type_taches]
        aType = TypeTache.find(id_type_tache)
        @animal.type_tache << aType
      end
    end

    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        @especes = Espece.all
        @status_animals = StatusAnimal.all
        @fermes = Ferme.where(user_id: current_user.id)
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT animals/1/remove_from_farm
  def remove_from_farm
    authorize! :update, @animal, :message => "Vous n'avez pas l'autorisation"
    @animal.update(ferme_id: nil)
    format.js { render :nothing => true }
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    authorize! :delete, @animal, :message => "Vous n'avez pas l'autorisation"

    for location in @animal.locations
      if(!(location.status_location == "Confirmé"))
        if (Date.today >= location.date && Date.today <= location.date + location.dureeJour)
          flash[:error] =  'Suppression impossible, cet animal est actuellement en location'
          redirect_to animal_path(@animal)
          return
        end
      end
    end

    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:nom, :status_animal_id, :prix_journalier, :ferme_id, :espece_id, :type_taches)
    end
end

coup_de_patte/app/helpers/animals_helper.rb
module AnimalsHelper
end

coup_de_patte/app/views/animals/_actions_specifiques.html.erb
<h2>Actions spécifiques</h2>
<% if action.eql?("index") %>
    <% if can? :manage, Animal %>
        <%= link_to 'Nouvel animal', new_animal_path %>
    <% end %>
<% end %>
<% if action.eql?("new") %>
    <%= link_to 'Retour', animals_path %>
<%end%>
<% if action.eql?("edit") %>
    <%= link_to 'Afficher', animal_path(@animal) %>
    <br />
    <% if can? :manage, Animal %>
        <%= link_to 'Nouvel animal', new_animal_path %>
    <% end %>
<%end%>
<% if action.eql?("show") %>
    <% if can? :manage, @animal %>
        <%= link_to 'Mettre à jour', edit_animal_path(@animal) %>
        <br />
    <% end %>


    <% if can? :manage, Animal %>
        <%= link_to 'Nouvel animal', new_animal_path %>
    <% end %>

  <!-- Vue Paysan -->
  <% if (@animal.status_animal.nom == 'disponible') %>
    <% if can? :create, Location %>
      <%= link_to 'Louer cet animal', new_location_path({:animal_id => @animal.id}) %>
      <br/>
    <% end %>
  <% end %>
<%end%>

coup_de_patte/app/views/animals/_animal.html.erb
  <td><%= animal.nom %></td>
  <td><%= animal.status_animal.nom %></td>
  <td><%= animal.prix_journalier %></td>
  <% if printFarm %>
      <% if animal.ferme.nil? %>
          <td>pas de ferme</td>
      <% else %>
          <td><%= link_to animal.ferme.nom, animal.ferme %></td>
      <% end %>
  <% end %>
  <td><%= animal.espece.nom %></td>

  <td>
    <% animal.type_tache.each_with_index do |tache, index| %>
        <%= if(index == animal.type_tache.size - 1)
              tache.nom
            else
              tache.nom + ", "
            end %>
    <% end %>
  </td>

  <td>
    <%= link_to 'Afficher', animal, :class => 'btn btn-sm btn-default' %>

    <% if can? :manage, animal %>
      <%= link_to 'Modifier', edit_animal_path(animal), :class => 'btn btn-sm btn-default' %>
      <%= link_to 'Détruire', animal, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger' %>
        <% if printRemoveFarm %>
          <%= link_to 'Remove from farm', remove_from_farm_animal_path(animal), :class => "removeFromFarm btn btn-sm btn-danger", method: :put, :data => { :remote => true } %>
        <% end %>
    <% end %>
  </td>

coup_de_patte/app/views/animals/_form.html.erb
<!-- we didn't manage to pass variable isRemote with false when render :new is called, so in that case the variable is not defined and the form is not remote -->
<%= form_for(@animal, :remote => (if (defined? isRemote) == "local-variable" then isRemote else false end)) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.collection_select :status_animal_id, @status_animals, :id, :nom %>
    </div>
  <div class="field">
    <%= f.label :prix_journalier %><br>
    <%= f.text_field :prix_journalier %>
  </div>
    <div class="field">
      <%= f.label :ferme %><br>
      <% if (defined? fixedFarm) == "local-variable" then %>
          <%= @animal.ferme.nom %>
          <%= f.hidden_field :ferme_id %>
      <% else %>
          <%= f.collection_select :ferme_id, @fermes, :id, :nom, {:include_blank => 'Selectionner'} %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :espece %><br>
      <%= f.collection_select :espece_id, @especes, :id, :nom %>
    </div>

    <%= f.label "Types de taches possible" %><br>
    <% for typeTache in TypeTache.all %>
        <div>
          <%= check_box_tag "animal[type_taches][]", typeTache.id, @animal.type_tache.include?(typeTache) %>
          <%= typeTache.nom %>
        </div>
    <% end %>
  <div class="actions">
    <%= f.submit :class => "btn btn-sm btn-default" %>
  </div>
<% end %>

coup_de_patte/app/views/animals/edit.html.erb
<% content_for :actions_specifiques do %>
    <%= render :partial => "actions_specifiques",
               :locals => {:action => "edit" } %>
<% end %>

<h1>Modification d'un animal</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @animal %> |
<%= link_to 'Retour', animals_path %>

coup_de_patte/app/views/animals/index.html.erb
<% content_for :actions_specifiques do %>
    <%= render :partial => "actions_specifiques", :locals => {:action => "index" } %>
<% end %>

<h1>Liste des animaux</h1>

<table class="table table-striped table-hover table-bordered table-responsive">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Status</th>
      <th>Prix journalier</th>
      <th>Ferme</th>
      <th>Espece</th>
      <th>Taches possibles</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <%= render :partial => "animal", :locals => {:animal => animal, :printFarm => true, :printRemoveFarm => false} %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :manage, Animal %>
    <%= link_to 'Nouvel animal', new_animal_path %>
<% end %>

coup_de_patte/app/views/animals/new.html.erb
<% content_for :actions_specifiques do %>
    <%= render :partial => "actions_specifiques",
               :locals => {:action => "new" } %>
<% end %>

<h1>Nouvel animal</h1>

<%= render 'form' %>

<%= link_to 'Retour', animals_path %>

coup_de_patte/app/views/animals/show.html.erb
<% content_for :actions_specifiques do %>
    <%= render :partial => "actions_specifiques",
               :locals => {:action => "show" } %>
<% end %>

<h1>Animal</h1>

<p>
  <strong>Nom:</strong>
  <%= @animal.nom %>
</p>

<p>
  <strong>Status:</strong>
  <%= @animal.status_animal.nom %>
</p>

<p>
  <strong>Prix journalier:</strong>
  <%= @animal.prix_journalier %>
</p>

<p>
  <strong>Ferme:</strong>
  <% if @animal.ferme.nil? %>
      pas de ferme
  <% else %>
    <%= link_to @animal.ferme.nom, @animal.ferme %>
  <% end %>
</p>

<p>
  <strong>Espece:</strong>
  <%= @animal.espece.nom %>
</p>

<p>
  <strong>Taches possibles :</strong>
  <ul>
    <% @animal.type_tache.each do |tache| %>
        <li>
          <%= tache.nom %>
        </li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Locations :</strong>

  <table class="table table-striped table-hover table-bordered table-responsive">
    <thead>
    <tr>
      <th>Date</th>
      <th>Durée (jours)</th>
      <th>Paysan</th>
      <th>Status de location</th>
      <th>Type de tâche</th>

      <!--<th colspan="2"></th>-->
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @animal.locations.each do |location| %>

      <!-- Pour Paysan-->
      <% if can? :create, location %>
        <% if ((location.date + location.dureeJour >= Date.today) && (location.status_location.id != 3))%>
          <tr>
            <td><%= location.date %></td>
            <td><%= location.dureeJour %></td>
            <td>
              <% if (location.user == current_user) %>
                <%= location.user.full_name %>
              <% else %>
                (confidentiel)
              <% end %>
            </td>
            <td><%= location.status_location.nom %></td>

            <td>
              <% location.type_tache.each_with_index do |tache, index| %>
                <% if (index == location.type_tache.size - 1) %>
                  <%= tache.nom %>
                <% else %>
                  <%= tache.nom + ', ' %>
                <% end %>
              <% end %>
            </td>

            <td>
              <%= link_to 'Afficher', location, :class => 'btn btn-sm btn-default' %>
            </td>
          </tr>
        <% end %>
      <% end %>

      <!-- Pour Gérant-->
      <% if can? :update, location %>
          <tr>
            <td><%= location.date %></td>
            <td><%= location.dureeJour %></td>
            <td><%= location.user.full_name %></td>
            <td><%= location.status_location.nom %></td>

            <td>
              <% location.type_tache.each_with_index do |tache, index| %>
                <% if (index == location.type_tache.size - 1) %>
                  <%= tache.nom %>
                <% else %>
                  <%= tache.nom + ', ' %>
                <% end %>
              <% end %>
            </td>

            <td>
              <%= link_to 'Afficher', location, :class => 'btn btn-sm btn-default' %>
              <%= link_to 'Modifier', edit_location_path(location), :class => 'btn btn-sm btn-default' %>
            </td>
          </tr>
      <% end %>

    <% end %>

    </tbody>
  </table>
</p>

<% if can? :manage, @animal %>
    <%= link_to 'Modifier', edit_animal_path(@animal) %> |
<% end %>
<%= link_to 'Retour', animals_path %>