coup_de_patte/config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  resources :locations, only: [:index, :show, :new, :create, :edit, :update]

  resources :type_taches

  resources :animals do
    member do
      put :remove_from_farm
    end
  end

  resources :fermes

  resources :especes

  root 'animals#index'

end

coup_de_patte/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)

    if user.has_role?(:Admin)
      can :read, :all

      can :manage, Espece
      can :manage, TypeTache

      can :voir_roles, User
    end

    if user.has_role?(:Gerant)
      can :read, :all

      #Gerant can manage his own farms
      can :manage, Ferme do |ferme|
        ferme.user.id == user.id
      end

      #Gerant can manage his own animals
      can :manage, Animal do |animal|
        animal.user.id == user.id
      end


      can :update, Location do |location|
        location.animal.user.id == user.id
      end
    end

    if user.has_role?(:Paysan)
      can :read, :all

      #Paysan peut louer un animal (créer une location)
      can :create, Location
    end
  end
end

coup_de_patte/app/models/admin.rb
class Admin < User
end

coup_de_patte/app/models/animal.rb
class Animal < ActiveRecord::Base
  has_and_belongs_to_many :type_tache
  belongs_to :status_animal
  belongs_to :espece
  belongs_to :ferme
  belongs_to :user
  has_many :locations

  validates_presence_of :nom
  validates_presence_of :status_animal
  validates_presence_of :prix_journalier
  validates_presence_of :user
  validates_presence_of :espece
end

coup_de_patte/app/models/espece.rb
class Espece < ActiveRecord::Base
  has_many :animals
  validates_presence_of :nom
end

coup_de_patte/app/models/ferme.rb
class Ferme < ActiveRecord::Base
  has_many :animals
  belongs_to :user
  validates_presence_of :nom
end

coup_de_patte/app/models/gerant.rb
class Gerant < User
  has_many :fermes
  has_many :animals
end

coup_de_patte/app/models/location.rb
class Location < ActiveRecord::Base
  has_and_belongs_to_many :type_tache
  belongs_to :status_location
  belongs_to :animal
  belongs_to :user

  validates_presence_of :date
  validates_presence_of :dureeJour
  validates_presence_of :animal
  validates_presence_of :user
  validates_presence_of :status_location
end

coup_de_patte/app/models/paysan.rb
class Paysan < User
  has_many :locations
end

coup_de_patte/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

coup_de_patte/app/models/status_animal.rb
class StatusAnimal < ActiveRecord::Base
  has_many :animals
  validates_presence_of :nom
end

coup_de_patte/app/models/status_location.rb
class StatusLocation < ActiveRecord::Base
  has_many :locations
  validates_presence_of :nom
end

coup_de_patte/app/models/type_tache.rb
class TypeTache < ActiveRecord::Base
  has_and_belongs_to_many :animals
  has_and_belongs_to_many :locations

  validates_presence_of :nom
end

coup_de_patte/app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles

  has_many :animals
  has_many :fermes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  def has_role?(role)
    # faire attention à la case, tous les modifications de case invalide la vérification de rôle
    # return self.roles.find_by(:name => role.to_s.upcase)

    return self.roles.find_by(:name => role.to_s)
  end

  def roles_as_text
    texte = ''
    self.roles.each do |role|
      texte = texte + role.name + ' '
    end

    return texte[0...-1] # enlever le dernier charactère
  end

  def full_name
    "#{prenom} #{nom}"
  end
end

coup_de_patte/app/helpers/animals_helper.rb
module AnimalsHelper
end

coup_de_patte/app/helpers/application_helper.rb
module ApplicationHelper
end

coup_de_patte/app/helpers/especes_helper.rb
module EspecesHelper
end

coup_de_patte/app/helpers/fermes_helper.rb
module FermesHelper
end

coup_de_patte/app/helpers/locations_helper.rb
module LocationsHelper
end

coup_de_patte/app/helpers/roles_helper.rb
module RolesHelper
end

coup_de_patte/app/helpers/users_helper.rb
module UsersHelper
end

coup_de_patte/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoupDePatte</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "_monstyle" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="page">
  <h1 id="siteTitle"><%= "Coup de patte" %></h1>

  <div class="user_nav">
    <% if user_signed_in? %>
        <h2>Connecté (<%= current_user.email %>, <%= current_user.roles_as_text %>)</h2>
        <%= link_to 'Déconnexion', destroy_user_session_path, :method => :delete %>
        |
        <%= link_to 'Modifiez vos données', edit_user_registration_path %>
    <% else %>
        <%= link_to 'Connexion', new_user_session_path %>
        |
        <%= link_to 'S\'enregistrer', new_user_registration_path %>
    <% end %>
  </div>

  <div class="content">
    <% if flash[:notice] %>
        <div class="notice_box">
          <%= flash[:notice] %>
        </div>
    <% end %>
    <% if flash[:error] %>
        <div class="error_box">
          <%= flash[:error] %>
        </div>
    <% end %>
    <%= yield %>
  </div>

  <div class="actions_specifiques">
    <%= yield :actions_specifiques %>
  </div>

  <div class="actions_generales">
    <h2>Actions générales</h2>
    <!-- Vue Public -->
    <%= link_to 'Liste des animaux', animals_path %>
    <br/>
    <%= link_to 'Liste des fermes', fermes_path %>
    <br/>

    <!--Vue Paysan-->
    <% if can? :create, Location %>
      <%= link_to 'Liste des locations', locations_path %>
      <br/>
    <% end %>

    <!-- Vue Gérant -->
    <% if can? :update, Location %>
        <%= link_to 'Gérer les locations', locations_path %>
        <br/>
    <% end %>

    <!-- Vue admin -->
    <% if can? :manage, TypeTache %>
        <%= link_to 'Liste des types de tache', type_taches_path %>
        <br/>
    <% end %>

    <% if can? :manage, Espece %>
        <%= link_to 'Liste des especes', especes_path %>
    <% end %>
  </div>

</div>

</body>
</html>